### ISSUE TITLE
Non-crashing fatal error handler

### ISSUE THREAD

**Issue by szhorvat** [igraph/python-igraph-ctypes#1]
With this new approach, is it feasible to set up `IGRAPH_FATAL()` to return to the top level instead of crashing? Both R and Mathematica have this. The way it works in Mathematica is the following:

 - The fatal error handler does a `longjmp` to a `jmp_buf` that's a global variable
 - There is an auto-generated wrapper for each igraph function that sets the global jump buffer (`setjmp`) before calling igraph, and serves as a return point for the `longjmp`

Note that Mathematica itself does not have any support for returning directly to the top level, like R does. I achieve this through these auto-generated wrappers.

**Comment by ntamas** [comment]
No, I think there's absolutely no guarantee that a `longjmp` would leave the Python interpreter in a consistent state. For one thing, reference counts would not be restored to the state they were before the `longjmp` was executed.
